FROM python:3.11

WORKDIR /app
COPY requirements.marketdata.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./libs/marketdata.py .

VOLUME [ "/app/configs" ]
CMD [ "python", "./marketdata.py", "/app/configs"]