name: research
channels:
  - defaults
dependencies:
  - ca-certificates
  - openssl
  - pip
  - python
  - sqlite
  - vc
  - vs2015_runtime
  - wheel
  - pip:
      - absl-py
      - adagio
      - aiodns
      - aiofiles
      - aiohttp
      - aiosignal
      - aiosqlite
      - alpha-vantage
      - altair
      - ansiwrap
      - antlr4-python3-runtime
      - anyio
      - appdirs
      - arch
      - argon2-cffi
      - argon2-cffi-bindings
      - arrow
      - ascii-magic
      - astropy
      - astropy-iers-data
      - asttokens
      - async-timeout
      - attrs
      - babel
      - backcall
      - backoff
      - backtesting
      - base58
      - beautifulsoup4
      - bleach
      - blinker
      - bokeh
      - brotli
      - bs4
      - bt
      - cachetools
      - catboost
      - ccxt
      - certifi
      - cffi
      - charset-normalizer
      - clarabel
      - click
      - cloudpickle
      - cmdstanpy
      - colorama
      - comm
      - commonmark
      - contourpy
      - convertdate
      - cryptography
      - cssselect
      - cssselect2
      - cvxpy
      - cycler
      - cython
      - dataclasses-json
      - dateparser
      - datetime
      - debugpy
      - decorator
      - defusedxml
      - degiro-connector
      - detecta
      - dnspython
      - ecdsa
      - ecos
      - entrypoints
      - ephem
      - et-xmlfile
      - exceptiongroup
      - exchange-calendars
      - executing
      - fastjsonschema
      - feedparser
      - ffmpeg-python
      - ffn
      - filelock
      - financedatabase
      - finnhub-python
      - finviz
      - finvizfinance
      - flake8
      - fonttools
      - formulaic
      - fqdn
      - fred
      - fredapi
      - frozendict
      - frozenlist
      - fs
      - fsspec
      - fugue
      - fugue-sql-antlr
      - fundamentalanalysis
      - future
      - gitdb
      - gitpython
      - google-auth
      - google-auth-oauthlib
      - greenlet
      - grpcio
      - h11
      - hijri-converter
      - holidays
      - html5lib
      - httpcore
      - httpx
      - huggingface-hub
      - idna
      - importlib-metadata
      - importlib-resources
      - inflection
      - interface-meta
      - intrinio-sdk
      - ipykernel
      - ipympl
      - ipython
      - ipython-genutils
      - ipywidgets
      - iso8601
      - isodate
      - isoduration
      - jedi
      - jinja2
      - joblib
      - json5
      - jsonpointer
      - jsonschema
      - jsonschema-specifications
      - jupyter-client
      - jupyter-core
      - jupyter-events
      - jupyter-server
      - jupyter-server-fileid
      - jupyter-server-ydoc
      - jupyter-ydoc
      - jupyterlab
      - jupyterlab-pygments
      - jupyterlab-server
      - jupyterlab-widgets
      - kiwisolver
      - korean-lunar-calendar
      - langchain
      - langsmith
      - lightgbm
      - lightning-utilities
      - linearmodels
      - llama-index
      - llvmlite
      - loguru
      - lunarcalendar
      - lxml
      - markdown
      - markupsafe
      - marshmallow
      - matplotlib
      - matplotlib-inline
      - mccabe
      - mistune
      - monotonic
      - more-itertools
      - mplfinance
      - mstarpy
      - multidict
      - multitasking
      - mutagen
      - mypy-extensions
      - nbclassic
      - nbclient
      - nbconvert
      - nbformat
      - nest-asyncio
      - networkx
      - nfoursid
      - nixtlats
      - nltk
      - notebook
      - notebook-shim
      - numba
      - numexpr
      - numpy
      - oandapyv20
      - oauthlib
      - onetimepass
      - openai
      - openai-whisper
      - openapi-schema-pydantic
      - openbb
      - openpyxl
      - osqp
      - packaging
      - pandas
      - pandas-datareader
      - pandas-market-calendars
      - pandas-ta
      - pandocfilters
      - papermill
      - parso
      - patsy
      - peewee
      - pickleshare
      - pillow
      - platformdirs
      - plotly
      - pmaw
      - pmdarima
      - posthog
      - praw
      - prawcore
      - prometheus-client
      - prompt-toolkit
      - property-cached
      - prophet
      - protobuf
      - psutil
      - pure-eval
      - pyarrow
      - pyasn1
      - pyasn1-modules
      - pybind11
      - pycares
      - pycodestyle
      - pycoingecko
      - pycparser
      - pycryptodome
      - pycryptodomex
      - pydantic
      - pydeck
      - pydeprecate
      - pyerfa
      - pyflakes
      - pygments
      - pyhdfe
      - pyluach
      - pymeeus
      - pyod
      - pyotp
      - pyparsing
      - pyprind
      - pyrsistent
      - pythclient
      - python-binance
      - python-coinmarketcap
      - python-dateutil
      - python-dotenv
      - python-graphviz
      - python-i18n
      - python-jose
      - python-json-logger
      - pytorch-lightning
      - pytrends
      - pytz
      - pywin32
      - pywinpty
      - pywry
      - pyyaml
      - pyzmq
      - qdldl
      - qpd
      - quandl
      - rdflib
      - referencing
      - regex
      - reportlab
      - requests
      - requests-futures
      - requests-oauthlib
      - retrying
      - rfc3339-validator
      - rfc3986-validator
      - rich
      - riskfolio-lib
      - robin-stocks
      - rpds-py
      - rsa
      - ruamel-yaml
      - ruamel-yaml-clib
      - scikit-learn
      - scipy
      - screeninfo
      - scs
      - seaborn
      - semantic-version
      - send2trash
      - setproctitle
      - setuptools
      - setuptools-rust
      - setuptools-scm
      - sgmllib3k
      - shap
      - six
      - slicer
      - smmap
      - sniffio
      - soupsieve
      - sparqlwrapper
      - sqlalchemy
      - sqlglot
      - squarify
      - stack-data
      - stanio
      - statsforecast
      - statsmodels
      - stocksera
      - streamlit
      - svglib
      - ta-lib
      - tabulate
      - tbats
      - tenacity
      - tensorboard
      - tensorboard-data-server
      - terminado
      - textwrap3
      - thepassiveinvestor
      - threadpoolctl
      - tiktoken
      - tinycss2
      - tokenizers
      - tokenterminal
      - toml
      - tomli
      - toolz
      - torch
      - torchmetrics
      - tornado
      - tqdm
      - tradingview-ta
      - traitlets
      - transformers
      - triad
      - types-python-dateutil
      - typing-extensions
      - typing-inspect
      - tzdata
      - tzlocal
      - u8darts
      - ujson
      - update-checker
      - uri-template
      - urllib3
      - user-agent
      - utilsforecast
      - vadersentiment
      - validators
      - valinvest
      - watchdog
      - wcwidth
      - webcolors
      - webencodings
      - websocket-client
      - websockets
      - werkzeug
      - widgetsnbextension
      - win32-setctime
      - wrapt
      - xarray
      - xgboost
      - xlsxwriter
      - xyzservices
      - y-py
      - yahooquery
      - yarl
      - yfinance
      - ypy-websocket
      - yt-dlp
      - zipp
      - zope-interface
